version: 2

# define sources
sources:
  - name: staging
    database: bigdata-fundamentals-project
    schema: gold # dataset

    tables:
      - name: cleaned_table # table

models:
  - name: stg_sales
    description: ""
    columns:
      - name: order_id
        data_type: string
        tests:
          # - unique:
          #     severity: warn
          - not_null:
              severity: warn
      - name: order_line_id
        data_type: string
      - name: order_datetime
        data_type: date
      - name: order_status
        data_type: string
      - name: coupon_code
        data_type: string
      - name: customer_id
        data_type: string
        tests:
          # - unique:
          #     severity: warn
          - not_null:
              severity: warn
      - name: customer_full_name
        data_type: string
      - name: customer_email
        data_type: string
      - name: customer_gender
        data_type: string
      - name: customer_region
        data_type: string
      - name: customer_signup_date
        data_type: string
      - name: store_id
        data_type: string
        tests:
          # - unique:
          #     severity: warn
          - not_null:
              severity: warn
      - name: store_name
        data_type: string
      - name: store_region
        data_type: string
      - name: store_rating
        data_type: float
      - name: product_sku
        data_type: string
        tests:
          # - unique:
          #     severity: warn
          - not_null:
              severity: warn
      - name: product_name
        data_type: string
      - name: brand
        data_type: string
      - name: category_name
        data_type: string
      - name: qty
        data_type: integer
      - name: list_price
        data_type: float
      - name: unit_price
        data_type: float
      - name: discount
        data_type: float
      - name: line_amount
        data_type: float
      - name: color
        data_type: string
      - name: weight_g
        data_type: string

        